# Generated by Django 6.0.4 on 2026-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Bank nomi')),
                ('foiz', models.FloatField(verbose_name='Yillik foiz stavkasi')),
                ('foyda', models.TextField(verbose_name='Ijobiy tomonlari')),
                ('zarar', models.TextField(verbose_name='Kamchiliklari/Risklar')),
            ],
            options={
                'verbose_name_plural': 'Banklar',
            },
        ),
    ]
